# Generated by Django 5.2.4 on 2025-07-12 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('text_number', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('country', models.CharField(default='US', max_length=2)),
                ('is_24_7', models.BooleanField(default=True)),
                ('languages', models.JSONField(default=list)),
                ('specialties', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrisisDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('detected_level', models.CharField(choices=[('concern', 'Concern - Needs support'), ('warning', 'Warning - Needs resources'), ('critical', 'Critical - Needs immediate help'), ('emergency', 'Emergency - Life threatening')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('context_factors', models.JSONField()),
                ('response_provided', models.TextField()),
                ('user_feedback', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('false_positive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCrisisProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_contact_method', models.CharField(default='text', max_length=20)),
                ('has_safety_plan', models.BooleanField(default=False)),
                ('safety_plan', models.TextField(blank=True)),
                ('triggers', models.JSONField(default=list)),
                ('coping_strategies', models.JSONField(default=list)),
                ('support_network', models.JSONField(default=dict)),
                ('last_crisis_check', models.DateTimeField(blank=True, null=True)),
                ('opt_out_auto_intervention', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
