# Generated by Django 5.2.4 on 2025-07-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='instructions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='type',
            field=models.CharField(choices=[('mindfulness', 'Mindfulness'), ('breathing', 'Breathing'), ('body_scan', 'Body Scan'), ('loving_kindness', 'Loving Kindness'), ('transcendental', 'Transcendental'), ('movement', 'Movement'), ('visualization', 'Visualization'), ('mantra', 'Mantra'), ('progressive_relaxation', 'Progressive Relaxation'), ('zen', 'Zen'), ('chakra', 'Chakra'), ('sound_bath', 'Sound Bath'), ('contemplative', 'Contemplative'), ('self_compassion', 'Self Compassion'), ('forgiveness', 'Forgiveness'), ('healing', 'Healing'), ('somatic', 'Somatic'), ('gazing', 'Gazing'), ('nature', 'Nature'), ('concentration', 'Concentration'), ('cognitive', 'Cognitive'), ('compassion', 'Compassion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='meditationrecommendation',
            name='mental_state_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meditation.usermentalstateanalysis'),
        ),
        migrations.AlterField(
            model_name='usermentalstateanalysis',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='usermentalstateanalysis',
            name='primary_concern',
            field=models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress'), ('anger', 'Anger'), ('grief', 'Grief'), ('insomnia', 'Insomnia'), ('focus', 'Focus Issues'), ('self_esteem', 'Low Self-Esteem'), ('trauma', 'Trauma'), ('panic', 'Panic'), ('burnout', 'Burnout'), ('loneliness', 'Loneliness'), ('energy', 'Energy'), ('balance', 'Balance'), ('vitality', 'Vitality'), ('healing', 'Healing'), ('emotions', 'Emotions'), ('intuition', 'Intuition'), ('feminine', 'Feminine'), ('cycles', 'Cycles'), ('workplace', 'Workplace'), ('tension', 'Tension'), ('parenting', 'Parenting'), ('patience', 'Patience'), ('mindfulness', 'Mindfulness'), ('presence', 'Presence'), ('rushing', 'Rushing'), ('creativity', 'Creativity'), ('freedom', 'Freedom'), ('worry', 'Worry'), ('rumination', 'Rumination'), ('overthinking', 'Overthinking'), ('disconnection', 'Disconnection'), ('fatigue', 'Fatigue'), ('grounding', 'Grounding'), ('relationships', 'Relationships'), ('guilt', 'Guilt'), ('resentment', 'Resentment'), ('expansion', 'Expansion'), ('consciousness', 'Consciousness'), ('spiritual', 'Spiritual'), ('appreciation', 'Appreciation'), ('seeking', 'Seeking'), ('restlessness', 'Restlessness'), ('clarity', 'Clarity'), ('peace', 'Peace'), ('wisdom', 'Wisdom'), ('liberation', 'Liberation'), ('awareness', 'Awareness'), ('phobias', 'Phobias'), ('pain', 'Pain'), ('addiction', 'Addiction'), ('eating_disorders', 'Eating Disorders'), ('instability', 'Instability'), ('change', 'Change'), ('seriousness', 'Seriousness'), ('joy', 'Joy'), ('surrender', 'Surrender'), ('connection', 'Connection'), ('acceptance', 'Acceptance'), ('self_love', 'Self Love'), ('shame', 'Shame'), ('stuck', 'Stuck'), ('empathy', 'Empathy'), ('loss', 'Loss'), ('sadness', 'Sadness'), ('performance', 'Performance'), ('confidence', 'Confidence'), ('achievement', 'Achievement'), ('psychic', 'Psychic'), ('children', 'Children'), ('relaxation', 'Relaxation'), ('bedtime', 'Bedtime'), ('sleep', 'Sleep'), ('morning', 'Morning'), ('routine', 'Routine'), ('busy', 'Busy'), ('heart_health', 'Heart Health'), ('bereavement', 'Bereavement'), ('immunity', 'Immunity'), ('ptsd', 'PTSD'), ('patterns', 'Patterns'), ('general_wellness', 'General Wellness'), ('positivity', 'Positivity'), ('negativity', 'Negativity'), ('digital_wellness', 'Digital Wellness'), ('phone_addiction', 'Phone Addiction'), ('vision', 'Vision'), ('pineal', 'Pineal')], max_length=30),
        ),
    ]
