# Generated by Django 5.2.4 on 2025-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_alter_meditation_instructions_alter_meditation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='content_source_id',
            field=models.CharField(blank=True, help_text='External content ID', max_length=100),
        ),
        migrations.AddField(
            model_name='meditation',
            name='content_warning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meditation',
            name='external_audio_url',
            field=models.URLField(blank=True, help_text='Spotify or other audio URL'),
        ),
        migrations.AddField(
            model_name='meditation',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meditation',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='meditation',
            name='requires_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or other video URL'),
        ),
        migrations.AddIndex(
            model_name='meditation',
            index=models.Index(fields=['source', 'type'], name='meditation__source_47d90e_idx'),
        ),
        migrations.AddIndex(
            model_name='meditation',
            index=models.Index(fields=['level', 'duration_minutes'], name='meditation__level_99d434_idx'),
        ),
        migrations.AddIndex(
            model_name='meditation',
            index=models.Index(fields=['effectiveness_score'], name='meditation__effecti_5e6459_idx'),
        ),
    ]
