# Generated by Django 5.2.4 on 2025-07-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0004_contentsyncjob_externalapiquota_externalcontentusage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='external_id',
            field=models.CharField(blank=True, help_text='External API ID', max_length=200, null=True),
        ),
    ]
